---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: rhsso
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhsso
  namespace: rhsso
spec:
  targetNamespaces:
  - rhsso
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhsso-operator.rhsso: ""
  name: rhsso-operator
  namespace: rhsso
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
...
