---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  labels:
    app.kubernetes.io/instance: rhdh-operator
  name: rhdh-operator
  namespace: rhdh-operator
spec:
  targetNamespaces:
  - rhdh-operator
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ""
  name: rhdh
  namespace: rhdh-operator
spec:
  installPlanApproval: Automatic
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
...
