---
- name: Deploy Hypershift cluster
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_namespace: clusters
    clusterset: default
    etcd_storage_size: 8Gi
    etcd_storage_class: nfs-csi
    cluster_network_cidr: 10.132.0.0/14
    service_network_cidr: 172.31.0.0/16
    # worker node settings
    worker_cores: 4
    worker_memory: 16Gi
    worker_disk: 32Gi

  tasks:
    - name: Deploy Hypershift cluster
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'hypershift_cluster.yml.j2') | from_yaml_all }}"
