---
- name: Create a VM on OCP-Virt.
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create a VirtualMachine with a DataVolume template
      redhat.openshift_virtualization.kubevirt_vm:
        state: "{{ vm_state }}"
        name: "{{ vm_name }}"
        namespace: "{{ vm_namespace }}"
        labels:
          app: "{{ vm_label }}"
        instancetype:
          name: "{{ vm_instancetype }}"   #u1.medium
        preference:
          name: "{{ vm_preference }}"              #fedora
        data_volume_templates:
          - metadata:
              name: "{{ vm_name }}"        #testdv
            spec:
              source:
                registry:
                  url: docker://quay.io/containerdisks/fedora:latest
              storage:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
        spec:
          domain:
            devices: {}
          volumes:
            - dataVolume:
                name: "{{ vm_name }}"
              name: datavolume
            - cloudInitNoCloud:
                userData: |-
                  #cloud-config
                  user: rhel
                  password: openshift
                  chpasswd:
                    expire: false
                  ssh_pwauth: true
              name: cloudinitdisk
        wait: true
        wait_timeout: 600
