---
- name: subscribe a vm to RHSM.
  hosts: all
  become: true
  tasks:
    - name: Register RHEL with Org ID and AK and auto-subscribe to available content.
      redhat.rhel_system_roles.redhat_subscription:
        state: present
        org_id: "{{ org_id }}"
        activationkey: "{{ activationkey }}"
        auto_attach: true