---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/aws-efs-operator.openshift-operators: ''
  name: aws-efs-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: aws-efs-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
...
