---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: devspaces
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: devspaces
  namespace: devspaces
spec:
  targetNamespaces:
    - devspaces
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform
  namespace: devspaces
spec:
  channel: 'stable'
  installPlanApproval: Automatic
  name: devspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace