---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
spec:
  destination:
    namespace: developerhub
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    path: setup/argocd
    repoURL: https://github.com/hammer-redhat/backvirt-boys
    targetRevision: jason-devel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-admin
  namespace: developerhub
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-backstage-secrets-admin
  namespace: developerhub
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-backstage-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-backstage-editor-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
...