---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customresources
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops 
    server: https://kubernetes.default.svc
  project: default
  source:
    path: setup/argocd/crs
    repoURL: https://github.com/hammer-redhat/backvirt-boys
    targetRevision: jason-devel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-admin
  namespace: ansible-automation-platform
rules:
  - apiGroups:
      - 'batch'
    resources:
      - 'jobs'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-aap-jobs-admin
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-admin
...
