---
apiVersion: v1
kind: Namespace
metadata:
  name: devspaces
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces
  namespace: openshift-gitops
spec:
  destination:
    namespace: devspaces
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    path: setup/argocd/devspaces
    repoURL: https://github.com/hammer-redhat/backvirt-boys
    targetRevision: jason-devel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: checluster-admin
  namespace: devspaces
rules:
  - apiGroups:
      - 'org.eclipse.che'
    resources:
      - 'checlusters'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-checluster-admin
  namespace: devspaces
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: checluster-admin
...
