---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: openshift-gitops
spec:
  destination:
    namespace: nfs
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
        - name: ""
          value: ""
    path: setup/argocd/nfs
    repoURL: https://github.com/hammer-redhat/backvirt-boys
    targetRevision: jason-devel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nfsprovisioners-admin
  namespace: nfs
rules:
  - apiGroups:
      - 'cache.jhouse.com'
    resources:
      - 'nfsprovisioners'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-nfsprovisioners-admin
  namespace: nfs
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nfsprovisioners-admin    
...
